import { useEffect, useState, type FormEvent } from "react";
import { loadPlanMonth, movePlanMoney, setCreditPaymentCategory, setPlanAssignment, type PlanSnapshot } from "../lib/desktop";
import { formatHuf, localCalendarMonth, shiftCalendarMonth } from "../lib/format";

export function PlanView() {
  const [month, setMonth] = useState(localCalendarMonth()); const [plan, setPlan] = useState<PlanSnapshot | null>(null); const [error, setError] = useState<string | null>(null); const [fromCategory, setFromCategory] = useState(""); const [toCategory, setToCategory] = useState(""); const [moveAmount, setMoveAmount] = useState("");
  async function reload() { setPlan(await loadPlanMonth(month)); }
  useEffect(() => { let active = true; setPlan(null); setError(null); loadPlanMonth(month).then((value) => { if (active) { setPlan(value); if (!value) setError("The Plan is available in the desktop app."); } }, () => { if (active) setError("Could not load this Plan month."); }); return () => { active = false; }; }, [month]);
  async function save(categoryId: string, value: string) { try { await setPlanAssignment(categoryId, month, BigInt(value.trim() || "0").toString()); await reload(); } catch { setError("Enter a whole HUF assignment amount."); } }
  async function move(event: FormEvent) { event.preventDefault(); try { const amount = BigInt(moveAmount.trim()); if (amount <= 0n) throw new Error(); await movePlanMoney(fromCategory, toCategory, month, amount.toString()); await reload(); setMoveAmount(""); setError(null); } catch { setError("Choose two categories and an amount available in the source category."); } }
  async function mapPayment(accountId: string, categoryId: string) { try { await setCreditPaymentCategory(accountId, categoryId); await reload(); } catch { setError("Could not save this credit-card payment category."); } }
  return <section className="plan-view" aria-labelledby="plan-title"><div className="plan-toolbar"><div><p className="eyebrow">MONTHLY PLAN</p><h2 id="plan-title">{month}</h2></div><div><button onClick={() => setMonth(shiftCalendarMonth(month, -1))}>←</button><button onClick={() => setMonth(localCalendarMonth())}>Today</button><button onClick={() => setMonth(shiftCalendarMonth(month, 1))}>→</button></div></div>{error && <p className="editor-error" role="alert">{error}</p>}{!plan ? <div className="register-message" role="status">Loading Plan…</div> : <><div className="plan-rta"><span>Ready to Assign</span><strong>{formatHuf(BigInt(plan.readyToAssign))}</strong></div><form className="plan-move" onSubmit={move}><strong>Move money</strong><select aria-label="Move money from" value={fromCategory} onChange={(event) => setFromCategory(event.target.value)}><option value="">From category</option>{plan.categories.map((category) => <option key={category.categoryId} value={category.categoryId}>{category.groupName} / {category.categoryName}</option>)}</select><select aria-label="Move money to" value={toCategory} onChange={(event) => setToCategory(event.target.value)}><option value="">To category</option>{plan.categories.map((category) => <option key={category.categoryId} value={category.categoryId}>{category.groupName} / {category.categoryName}</option>)}</select><input aria-label="Move amount" value={moveAmount} onChange={(event) => setMoveAmount(event.target.value)} placeholder="HUF" inputMode="numeric" /><button disabled={!fromCategory || !toCategory || !moveAmount}>Move</button></form>{plan.creditPaymentCategories.length > 0 && <div className="plan-credit"><strong>Credit card payment categories</strong>{plan.creditPaymentCategories.map((mapping) => <label key={mapping.accountId}>{mapping.accountName}<select value={mapping.categoryId ?? ""} onChange={(event) => { if (event.target.value) void mapPayment(mapping.accountId, event.target.value); }}><option value="">Choose payment category</option>{plan.categories.map((category) => <option key={category.categoryId} value={category.categoryId}>{category.groupName} / {category.categoryName}</option>)}</select></label>)}</div>}<div className="plan-table"><div className="plan-head"><span>Category</span><span>Assigned</span><span>Activity</span><span>Available</span></div>{plan.categories.map((category) => <div className="plan-row" key={category.categoryId}><span><small>{category.groupName}</small>{category.categoryName}</span><input aria-label={`${category.categoryName} assigned`} defaultValue={category.assigned} onKeyDown={(event) => { if (event.key === "Enter") event.currentTarget.blur(); }} onBlur={(event) => { if (event.target.value !== category.assigned) void save(category.categoryId, event.target.value); }} /><span>{formatHuf(BigInt(category.activity))}</span><strong>{formatHuf(BigInt(category.available))}</strong></div>)}</div></>}</section>;
}
