import { useEffect, useState, type FormEvent } from "react";
import { createMonthlySchedule, deactivateSchedule, loadScheduledOccurrences, postScheduledOccurrence, skipScheduledOccurrence, type AccountOverview, type ScheduledOccurrence, type TransactionFormOptions } from "../lib/desktop";
import { formatDate, formatHuf, localCalendarDate, parseSignedHufInput } from "../lib/format";
export const SAFETY_BACKUP_ERROR = "Could not create the required safety backup. No changes were made.";

export function scheduleCancellationError(caught: unknown): string {
  return caught === SAFETY_BACKUP_ERROR ? SAFETY_BACKUP_ERROR : "This schedule could not be canceled.";
}
export function ScheduleView({ accounts, options }: { accounts: AccountOverview[]; options: TransactionFormOptions }) {
  const [items, setItems] = useState<ScheduledOccurrence[] | null>(null); const [error, setError] = useState<string | null>(null); const [accountId, setAccountId] = useState(accounts[0]?.id ?? ""); const [startDate, setStartDate] = useState(localCalendarDate()); const [endDate, setEndDate] = useState(""); const [payeeName, setPayeeName] = useState(""); const [categoryId, setCategoryId] = useState(""); const [memo, setMemo] = useState(""); const [amount, setAmount] = useState("");
  async function reload() { setItems(await loadScheduledOccurrences()); } useEffect(() => { void reload(); }, []);
  async function save(event: FormEvent) { event.preventDefault(); try { const value = parseSignedHufInput(amount); if (!accountId || value === 0n) throw new Error(); await createMonthlySchedule({ accountId, startDate, endDate: endDate || null, payeeName: payeeName || null, categoryId: categoryId || null, memo, flagId: null, amount: value.toString() }); setAmount(""); await reload(); } catch { setError("Choose an account, valid date, and non-zero whole HUF amount."); } }
  async function finish(id: string, post: boolean) { try { if (post) await postScheduledOccurrence(id); else await skipScheduledOccurrence(id); await reload(); } catch { setError("This scheduled occurrence could not be updated."); } }
  async function cancel(scheduleId: string) { try { await deactivateSchedule(scheduleId); await reload(); } catch (caught) { setError(scheduleCancellationError(caught)); } }
  return <section className="schedule-view"><div className="plan-toolbar"><div><p className="eyebrow">SCHEDULED TRANSACTIONS</p><h2>Monthly schedules</h2></div></div>{error && <p className="editor-error" role="alert">{error}</p>}<form className="schedule-form" onSubmit={save}><strong>New monthly schedule</strong><select value={accountId} onChange={(event) => setAccountId(event.target.value)}>{accounts.filter((account) => !account.closed).map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select><input type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)} /><input type="date" value={endDate} onChange={(event) => setEndDate(event.target.value)} title="Optional end date" /><input value={payeeName} onChange={(event) => setPayeeName(event.target.value)} placeholder="Payee" /><select value={categoryId} onChange={(event) => setCategoryId(event.target.value)}><option value="">Uncategorized</option>{options.categories.map((category) => <option key={category.id} value={category.id}>{category.groupName} / {category.name}</option>)}</select><input value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="HUF, - for outflow" /><input value={memo} onChange={(event) => setMemo(event.target.value)} placeholder="Memo" /><button>Schedule</button></form>{items === null ? <div className="register-message">Loading schedules…</div> : <div className="schedule-list">{items.length === 0 ? <p>No pending scheduled transactions.</p> : items.map((item) => <div key={item.transactionId}><span><strong>{formatDate(item.date)}</strong> {item.accountName} · {item.payeeName ?? "No payee"}<small>{item.categoryName ?? "Uncategorized"}{item.memo && ` · ${item.memo}`}</small></span><b>{formatHuf(BigInt(item.amount))}</b><button onClick={() => void finish(item.transactionId, true)}>Post</button><button onClick={() => void finish(item.transactionId, false)}>Skip</button><button onClick={() => void cancel(item.scheduleId)}>Cancel</button></div>)}</div>}</section>;
}
